[package]
name = "Twitch-AI-Chatbot"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.8"
log = "0.4.28"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_yml = "0.0.12"
