Twitch:
  host: irc-ws.chat.twitch.tv

Accounts:
  - oauth: oauth:hogehoge
    account_name: username
    channel: channeltospeak
    instruction: instructions/template.json
    gpt_model: gpt-5-nano
    #! operating mode is either ALWAYS, ONLINE, and OFFLINE
    operating_mode: ALWAYS
    interval: 60
    timeout: 300
    chat_history_size: 5
    proxy:
      host: http://0.0.0.0:80
      username: hogehoge
      password: hogehoge

OpenAI:
  api_key: sk-
