Twitch:
  host: irc-ws.chat.twitch.tv

Accounts:
  - oauth: oauth:hogehoge
    account_name: username
    channel: channeltospeak
    instruction: instructions/template.json
    gpt_model: gpt-5-nano
    proxy:
      host: http://0.0.0.0:80
      username: hogehoge
      password: hogehoge

OpenAI:
  api_key: sk-
